services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-hardcore
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ENABLE_WHITELIST: "TRUE"
      DIFFICULTY: hard
      HARDCORE: "false"
      MODE: survival
      MAX_PLAYERS: 20
      MOTD: "NuckChorris Minecraft Server"
      TYPE: "vanilla"   # You can change this to "paper", "spigot", etc., if you want plugins
      PVP: "false"
      OPS: "PapiiChulo1"
      MEMORY: "8G"
      INIT_MEMORY: "8G"
      TZ: "America/Denver"
    volumes:
      - ./minecraft_hardcore:/data
    restart: unless-stopped