services:
  minecraft-fabric:
    image: itzg/minecraft-server
    container_name: minecraft-hardcore-fabric
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      DIFFICULTY: hard
      MODE: survival
      MAX_PLAYERS: 20
      MOTD: "NuckChorris Always Hard Minecraft Server"
      TYPE: "FABRIC"
      PVP: "false"
      OPS: "PapiiChulo1"
      MEMORY: "10G"
      JVM_OPTS: "-Xms2G -Xmx10G -XX:+UseG1GC"
      TZ: "America/Denver"
      FABRIC_VERSION: "0.14.16"
    volumes:
      - ./minecraft_hardcore:/data
      - ./minecraft_hardcore/mods:/data/mods
    restart: unless-stopped