- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: sunday
        - type: weather
          location: West Jordan
          units: imperial # alternatively "imperial"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true
        - type: twitch-channels
          channels:
            - theprimeagen
            - j_blow
            - piratesoftware
            - cohhcarnage
            - christitustech
            - EJ_SA

    - size: full
      widgets:
        - type: group
        - type: monitor
          cache: 1m
          title: homelab
          sites:
            - title: Proxmox
              url: https://proxmox.local.paninilab.org
              icon: /assets/proxmox.png
            - title: Unifi
              url:  https://unifi.local.paninilab.org
              icon: /assets/unifi.svg
            - title: TrueNAS Scale
              url: https://truenas.local.paninilab.org
              icon: /assets/truenas.png
            - title: Proxmox Backup Server
              url: https://pbs.local.paninilab.org
              icon: /assets/pbs.png
            - title: NGINX Proxy Manager
              url: https://nginx.local.paninilab.org
              icon: /assets/nginx.png
            - title: Portainer
              url: https://portainer.local.paninilab.org
              icon: /assets/portainer.png
            - title: Dozzle
              url: https://dozzle.local.paninilab.org
              icon: /assets/dozzle.svg
            # - title: Pi-Hole
            #   url: https://192.168.1.10/admin
            #   icon: /assets/pihole.svg
            - title: Uptime Kuma
              url: https://uptime.local.paninilab.org
              icon: /assets/uptimekuma.svg
            - title: Kasm Workspaces
              url: https://kasm.local.paninilab.org
              icon: /assets/kasm.svg
            - title: Immich
              url: https://immich.local.paninilab.org
              icon: /assets/immich.svg
            - title: Mealie
              url: https://mealie.local.paninilab.org
              icon: /assets/mealie.svg
            - title: Audiobook Shelf
              url: https://books.local.paninilab.org
              icon: /assets/audiobookshelf.svg
        - type: monitor
          cache: 1m
          title: arr
          sites:
            - title: Readarr
              url: https://readarr.local.paninilab.org
              icon: /assets/readarr.svg
            - title: Prowlarr
              url: https://prowlarr.local.paninilab.org
              icon: /assets/prowlarr.svg
            - title: qBittorrent
              url: https://torrent.local.paninilab.org
              icon: /assets/qbittorrent.svg
        - type: videos
          channels:
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

    - size: small
      widgets:
        - type: dns-stats
          service: pihole
          url: https://192.168.1.10
          token: ${PIHOLE_TOKEN}
          password: ${PIHOLE_PASSWORD}

        - type: custom-api
          title: Immich stats
          cache: 1d
          url: https://immich.local.paninilab.org/api/server/statistics
          headers:
            x-api-key: ${IMMICH_API_KEY}
            Accept: application/json
          template: |
            <div class="flex justify-between text-center">
              <div>
                  <div class="color-highlight size-h3">{{ .JSON.Int "photos" | formatNumber }}</div>
                  <div class="size-h6">PHOTOS</div>
              </div>
              <div>
                  <div class="color-highlight size-h3">{{ .JSON.Int "videos" | formatNumber }}</div>
                  <div class="size-h6">VIDEOS</div>
              </div>
              <div>
                  <div class="color-highlight size-h3">{{ div (.JSON.Int "usage" | toFloat) 1073741824 | toInt | formatNumber }}GB</div>
                  <div class="size-h6">USAGE</div>
              </div>
            </div>
            
        - type: custom-api
          cache: 1h
          title: Internet Speed
          url: http://${SPEEDTEST_API_URL}/api/v1/results/latest
          headers:
            Authorization: Bearer ${SPEEDTEST_TRACKER_API_TOKEN}
            Accept: application/json
          template: |
            <div class="flex justify-between text-center margin-block-3">
                <div>
                    <div class="color-highlight size-h3">{{ .JSON.Float "data.download_bits" | mul 0.000001 | printf "%.1f" }}</div>
                    <div class="size-h6">DOWNLOAD</div>
                </div>
                <div>
                    <div class="color-highlight size-h3">{{ .JSON.Float "data.upload_bits" | mul 0.000001 | printf "%.1f" }}</div>
                    <div class="size-h6">UPLOAD</div>
                </div>
                <div>
                    <div class="color-highlight size-h3">{{ .JSON.Float "data.ping" | printf "%.0f ms" }}</div>
                    <div class="size-h6">PING</div>
                </div>
            </div>

        - type: markets
          # The link to go to when clicking on the symbol in the UI,
          # {SYMBOL} will be substituded with the symbol for each market
          symbol-link-template: https://www.tradingview.com/symbols/{SYMBOL}/news
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: MSFT
              name: Microsoft
        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - glanceapp/glance
            - go-gitea/gitea
            - immich-app/immich
            - syncthing/syncthing
